### ISSUE TITLE
byteorder test fails on BE architectures

### ISSUE THREAD

**Issue by ignatenkobrain** [BurntSushi/byteorder#102]
```
failures:
---- stdtests::prop_ext_int_1::native_endian stdout ----
	thread 'stdtests::prop_ext_int_1::native_endian' panicked at '[quickcheck] TEST FAILED. Arguments: (1)', /usr/share/cargo/registry/quickcheck-0.4.1/src/tester.rs:147:27
note: Run with `RUST_BACKTRACE=1` for a backtrace.
---- stdtests::prop_ext_int_2::native_endian stdout ----
	thread 'stdtests::prop_ext_int_2::native_endian' panicked at '[quickcheck] TEST FAILED. Arguments: (1)', /usr/share/cargo/registry/quickcheck-0.4.1/src/tester.rs:147:27
---- stdtests::prop_ext_int_3::native_endian stdout ----
	thread 'stdtests::prop_ext_int_3::native_endian' panicked at '[quickcheck] TEST FAILED. Arguments: (1)', /usr/share/cargo/registry/quickcheck-0.4.1/src/tester.rs:147:27
---- stdtests::prop_ext_int_4::native_endian stdout ----
	thread 'stdtests::prop_ext_int_4::native_endian' panicked at '[quickcheck] TEST FAILED. Arguments: (1)', /usr/share/cargo/registry/quickcheck-0.4.1/src/tester.rs:147:27
---- stdtests::prop_ext_int_5::native_endian stdout ----
	thread 'stdtests::prop_ext_int_5::native_endian' panicked at '[quickcheck] TEST FAILED. Arguments: (1)', /usr/share/cargo/registry/quickcheck-0.4.1/src/tester.rs:147:27
---- stdtests::prop_ext_int_6::native_endian stdout ----
	thread 'stdtests::prop_ext_int_6::native_endian' panicked at '[quickcheck] TEST FAILED. Arguments: (1)', /usr/share/cargo/registry/quickcheck-0.4.1/src/tester.rs:147:27
---- stdtests::prop_ext_int_7::native_endian stdout ----
	thread 'stdtests::prop_ext_int_7::native_endian' panicked at '[quickcheck] TEST FAILED. Arguments: (1)', /usr/share/cargo/registry/quickcheck-0.4.1/src/tester.rs:147:27
---- stdtests::prop_ext_uint_1::native_endian stdout ----
	thread 'stdtests::prop_ext_uint_1::native_endian' panicked at '[quickcheck] TEST FAILED. Arguments: (1)', /usr/share/cargo/registry/quickcheck-0.4.1/src/tester.rs:147:27
---- stdtests::prop_ext_uint_2::native_endian stdout ----
	thread 'stdtests::prop_ext_uint_2::native_endian' panicked at '[quickcheck] TEST FAILED. Arguments: (1)', /usr/share/cargo/registry/quickcheck-0.4.1/src/tester.rs:147:27
---- stdtests::prop_ext_uint_3::native_endian stdout ----
	thread 'stdtests::prop_ext_uint_3::native_endian' panicked at '[quickcheck] TEST FAILED. Arguments: (1)', /usr/share/cargo/registry/quickcheck-0.4.1/src/tester.rs:147:27
---- stdtests::prop_ext_uint_4::native_endian stdout ----
	thread 'stdtests::prop_ext_uint_4::native_endian' panicked at '[quickcheck] TEST FAILED. Arguments: (1)', /usr/share/cargo/registry/quickcheck-0.4.1/src/tester.rs:147:27
---- stdtests::prop_ext_uint_5::native_endian stdout ----
	thread 'stdtests::prop_ext_uint_5::native_endian' panicked at '[quickcheck] TEST FAILED. Arguments: (1)', /usr/share/cargo/registry/quickcheck-0.4.1/src/tester.rs:147:27
---- stdtests::prop_ext_uint_7::native_endian stdout ----
	thread 'stdtests::prop_ext_uint_7::native_endian' panicked at '[quickcheck] TEST FAILED. Arguments: (1)', /usr/share/cargo/registry/quickcheck-0.4.1/src/tester.rs:147:27
---- stdtests::prop_ext_uint_6::native_endian stdout ----
	thread 'stdtests::prop_ext_uint_6::native_endian' panicked at '[quickcheck] TEST FAILED. Arguments: (1)', /usr/share/cargo/registry/quickcheck-0.4.1/src/tester.rs:147:27
failures:
    stdtests::prop_ext_int_1::native_endian
    stdtests::prop_ext_int_2::native_endian
    stdtests::prop_ext_int_3::native_endian
    stdtests::prop_ext_int_4::native_endian
    stdtests::prop_ext_int_5::native_endian
    stdtests::prop_ext_int_6::native_endian
    stdtests::prop_ext_int_7::native_endian
    stdtests::prop_ext_uint_1::native_endian
    stdtests::prop_ext_uint_2::native_endian
    stdtests::prop_ext_uint_3::native_endian
    stdtests::prop_ext_uint_4::native_endian
    stdtests::prop_ext_uint_5::native_endian
    stdtests::prop_ext_uint_6::native_endian
    stdtests::prop_ext_uint_7::native_endian
test result: FAILED. 324 passed; 14 failed; 0 ignored; 0 measured; 0 filtered out
```

This one was from s390x machine.

**Comment by cuviper** [comment]
The [`big_endian` test](https://github.com/BurntSushi/byteorder/blob/master/src/lib.rs#L2863-L2874) creates a new `rdr` vector with just the later bytes, but the following `native_endian` test behaves just like the `little_endian` test -- which is inappropriate on actual big-endian machines.
