### ISSUE TITLE
Multiple byteorder tests are failing on Fedora (literal out of range)

### ISSUE THREAD

**Issue by ignatenkobrain** [BurntSushi/byteorder#152]
```rust
failures:
---- src/lib.rs - ByteOrder (line 199) stdout ----
error: literal out of range for i16
 --> src/lib.rs:203:33
  |
7 | BigEndian::write_i16(&mut buf, -50_000);
  |                                 ^^^^^^
  |
  = note: #[deny(overflowing_literals)] on by default
error: literal out of range for i16
 --> src/lib.rs:204:13
  |
8 | assert_eq!(-50_000, BigEndian::read_i16(&buf));
  |             ^^^^^^
error: aborting due to 2 previous errors
thread 'src/lib.rs - ByteOrder (line 199)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
---- src/lib.rs - ByteOrder::from_slice_i16 (line 1663) stdout ----
error: literal out of range for i16
 --> src/lib.rs:1666:23
  |
6 | let mut numbers = [5, 65000];
  |                       ^^^^^
  |
  = note: #[deny(overflowing_literals)] on by default
error: literal out of range for i16
 --> src/lib.rs:1668:36
  |
8 | assert_eq!(numbers, [5i16.to_be(), 65000i16.to_be()]);
  |                                    ^^^^^^^^
error: aborting due to 2 previous errors
thread 'src/lib.rs - ByteOrder::from_slice_i16 (line 1663)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
---- src/lib.rs - ByteOrder::read_f64_into (line 1257) stdout ----
error: literal out of range for f64
 --> src/lib.rs:1261:32
  |
7 | let numbers_given = [1.0, 2.0, 31.312e311, -11.32e91];
  |                                ^^^^^^^^^^
  |
  = note: #[deny(overflowing_literals)] on by default
error: aborting due to previous error
thread 'src/lib.rs - ByteOrder::read_f64_into (line 1257)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
---- src/lib.rs - ByteOrder::read_f64_into_unchecked (line 1291) stdout ----
warning: use of deprecated item 'byteorder::ByteOrder::read_f64_into_unchecked': please use `read_f64_into` instead
  --> src/lib.rs:1299:1
   |
11 | LittleEndian::read_f64_into_unchecked(&bytes, &mut numbers_got);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(deprecated)] on by default
error: literal out of range for f64
 --> src/lib.rs:1295:32
  |
7 | let numbers_given = [1.0, 2.0, 31.312e311, -11.32e91];
  |                                ^^^^^^^^^^
  |
  = note: #[deny(overflowing_literals)] on by default
error: aborting due to previous error
thread 'src/lib.rs - ByteOrder::read_f64_into_unchecked (line 1291)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
---- src/lib.rs - ByteOrder::read_i16_into (line 1078) stdout ----
error: literal out of range for i16
 --> src/lib.rs:1082:28
  |
7 | let numbers_given = [1, 2, 0xf00f, 0xffee];
  |                            ^^^^^^
  |
  = note: #[deny(overflowing_literals)] on by default
  = note: the literal `0xf00f` (decimal `61455`) does not fit into an `i16` and will become `-4081i16`
  = help: consider using `u16` instead
error: literal out of range for i16
 --> src/lib.rs:1082:36
  |
7 | let numbers_given = [1, 2, 0xf00f, 0xffee];
  |                                    ^^^^^^
  |
  = note: the literal `0xffee` (decimal `65518`) does not fit into an `i16` and will become `-18i16`
  = help: consider using `u16` instead
error: aborting due to 2 previous errors
thread 'src/lib.rs - ByteOrder::read_i16_into (line 1078)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
---- src/lib.rs - ByteOrder::write_f64_into (line 1556) stdout ----
error: literal out of range for f64
 --> src/lib.rs:1560:32
  |
7 | let numbers_given = [1.0, 2.0, 31.312e311, -11.32e91];
  |                                ^^^^^^^^^^
  |
  = note: #[deny(overflowing_literals)] on by default
error: aborting due to previous error
thread 'src/lib.rs - ByteOrder::write_f64_into (line 1556)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
---- src/lib.rs - ByteOrder::write_i16_into (line 1411) stdout ----
error: literal out of range for i16
 --> src/lib.rs:1415:28
  |
7 | let numbers_given = [1, 2, 0xf00f, 0xffee];
  |                            ^^^^^^
  |
  = note: #[deny(overflowing_literals)] on by default
  = note: the literal `0xf00f` (decimal `61455`) does not fit into an `i16` and will become `-4081i16`
  = help: consider using `u16` instead
error: literal out of range for i16
 --> src/lib.rs:1415:36
  |
7 | let numbers_given = [1, 2, 0xf00f, 0xffee];
  |                                    ^^^^^^
  |
  = note: the literal `0xffee` (decimal `65518`) does not fit into an `i16` and will become `-18i16`
  = help: consider using `u16` instead
error: aborting due to 2 previous errors
thread 'src/lib.rs - ByteOrder::write_i16_into (line 1411)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
---- src/lib.rs - ByteOrder::write_u16 (line 371) stdout ----
error: literal out of range for u16
 --> src/lib.rs:375:35
  |
7 | LittleEndian::write_u16(&mut buf, 1_000_000);
  |                                   ^^^^^^^^^
  |
  = note: #[deny(overflowing_literals)] on by default
error: literal out of range for u16
 --> src/lib.rs:376:12
  |
8 | assert_eq!(1_000_000, LittleEndian::read_u16(&buf));
  |            ^^^^^^^^^
error: aborting due to 2 previous errors
thread 'src/lib.rs - ByteOrder::write_u16 (line 371)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
---- src/lib.rs - NetworkEndian (line 1844) stdout ----
error: literal out of range for i16
 --> src/lib.rs:1848:33
  |
7 | BigEndian::write_i16(&mut buf, -50_000);
  |                                 ^^^^^^
  |
  = note: #[deny(overflowing_literals)] on by default
error: literal out of range for i16
 --> src/lib.rs:1849:13
  |
8 | assert_eq!(-50_000, NetworkEndian::read_i16(&buf));
  |             ^^^^^^
error: aborting due to 2 previous errors
thread 'src/lib.rs - NetworkEndian (line 1844)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
failures:
    src/lib.rs - ByteOrder (line 199)
    src/lib.rs - ByteOrder::from_slice_i16 (line 1663)
    src/lib.rs - ByteOrder::read_f64_into (line 1257)
    src/lib.rs - ByteOrder::read_f64_into_unchecked (line 1291)
    src/lib.rs - ByteOrder::read_i16_into (line 1078)
    src/lib.rs - ByteOrder::write_f64_into (line 1556)
    src/lib.rs - ByteOrder::write_i16_into (line 1411)
    src/lib.rs - ByteOrder::write_u16 (line 371)
    src/lib.rs - NetworkEndian (line 1844)
test result: FAILED. 111 passed; 9 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by ignatenkobrain** [comment]
Oh, this is probably duplicate of #144, let me check fix for that.
